#pragma once

// From glfw3.h
#define PRIMAL_MOUSE_BUTTON_1         0
#define PRIMAL_MOUSE_BUTTON_2         1
#define PRIMAL_MOUSE_BUTTON_3         2
#define PRIMAL_MOUSE_BUTTON_4         3
#define PRIMAL_MOUSE_BUTTON_5         4
#define PRIMAL_MOUSE_BUTTON_6         5
#define PRIMAL_MOUSE_BUTTON_7         6
#define PRIMAL_MOUSE_BUTTON_8         7
#define PRIMAL_MOUSE_BUTTON_LAST      PRIMAL_MOUSE_BUTTON_8
#define PRIMAL_MOUSE_BUTTON_LEFT      PRIMAL_MOUSE_BUTTON_1
#define PRIMAL_MOUSE_BUTTON_RIGHT     PRIMAL_MOUSE_BUTTON_2
#define PRIMAL_MOUSE_BUTTON_MIDDLE    PRIMAL_MOUSE_BUTTON_3
