#pragma once

#include "core/primal_string.h"
namespace pm {

enum OS_Key {
	OS_Key_Null,
	OS_Key_Esc,
	OS_Key_F1,
	OS_Key_F2,
	OS_Key_F3,
	OS_Key_F4,
	OS_Key_F5,
	OS_Key_F6,
	OS_Key_F7,
	OS_Key_F8,
	OS_Key_F9,
	OS_Key_F10,
	OS_Key_F11,
	OS_Key_F12,
	OS_Key_F13,
	OS_Key_F14,
	OS_Key_F15,
	OS_Key_F16,
	OS_Key_F17,
	OS_Key_F18,
	OS_Key_F19,
	OS_Key_F20,
	OS_Key_F21,
	OS_Key_F22,
	OS_Key_F23,
	OS_Key_F24,
	OS_Key_GraveAccent,
	OS_Key_0,
	OS_Key_1,
	OS_Key_2,
	OS_Key_3,
	OS_Key_4,
	OS_Key_5,
	OS_Key_6,
	OS_Key_7,
	OS_Key_8,
	OS_Key_9,
	OS_Key_Minus,
	OS_Key_Equal,
	OS_Key_Backspace,
	OS_Key_Delete,
	OS_Key_Tab,
	OS_Key_A,
	OS_Key_B,
	OS_Key_C,
	OS_Key_D,
	OS_Key_E,
	OS_Key_F,
	OS_Key_G,
	OS_Key_H,
	OS_Key_I,
	OS_Key_J,
	OS_Key_K,
	OS_Key_L,
	OS_Key_M,
	OS_Key_N,
	OS_Key_O,
	OS_Key_P,
	OS_Key_Q,
	OS_Key_R,
	OS_Key_S,
	OS_Key_T,
	OS_Key_U,
	OS_Key_V,
	OS_Key_W,
	OS_Key_X,
	OS_Key_Y,
	OS_Key_Z,
	OS_Key_Space,
	OS_Key_Enter,
	OS_Key_Ctrl,
	OS_Key_Shift,
	OS_Key_Alt,
	OS_Key_Up,
	OS_Key_Left,
	OS_Key_Down,
	OS_Key_Right,
	OS_Key_PageUp,
	OS_Key_PageDown,
	OS_Key_Home,
	OS_Key_End,
	OS_Key_ForwardSlash,
	OS_Key_Period,
	OS_Key_Comma,
	OS_Key_Quote,
	OS_Key_LeftBracket,
	OS_Key_RightBracket,
	OS_Key_Insert,
	OS_Key_MouseLeft,
	OS_Key_MouseMiddle,
	OS_Key_MouseRight,
	OS_Key_Semicolon,
	OS_Key_COUNT,
};

static const String8 osKeyStringTable[92] = {
	Str8L("Null"),
	Str8L("Escape"),
	Str8L("F1"),
	Str8L("F2"),
	Str8L("F3"),
	Str8L("F4"),
	Str8L("F5"),
	Str8L("F6"),
	Str8L("F7"),
	Str8L("F8"),
	Str8L("F9"),
	Str8L("F10"),
	Str8L("F11"),
	Str8L("F12"),
	Str8L("F13"),
	Str8L("F14"),
	Str8L("F15"),
	Str8L("F16"),
	Str8L("F17"),
	Str8L("F18"),
	Str8L("F19"),
	Str8L("F20"),
	Str8L("F21"),
	Str8L("F22"),
	Str8L("F23"),
	Str8L("F24"),
	Str8L("Grave Accent"),
	Str8L("0"),
	Str8L("1"),
	Str8L("2"),
	Str8L("3"),
	Str8L("4"),
	Str8L("5"),
	Str8L("6"),
	Str8L("7"),
	Str8L("8"),
	Str8L("9"),
	Str8L("Minus"),
	Str8L("Equal"),
	Str8L("Backspace"),
	Str8L("Delete"),
	Str8L("Tab"),
	Str8L("A"),
	Str8L("B"),
	Str8L("C"),
	Str8L("D"),
	Str8L("E"),
	Str8L("F"),
	Str8L("G"),
	Str8L("H"),
	Str8L("I"),
	Str8L("J"),
	Str8L("K"),
	Str8L("L"),
	Str8L("M"),
	Str8L("N"),
	Str8L("O"),
	Str8L("P"),
	Str8L("Q"),
	Str8L("R"),
	Str8L("S"),
	Str8L("T"),
	Str8L("U"),
	Str8L("V"),
	Str8L("W"),
	Str8L("X"),
	Str8L("Y"),
	Str8L("Z"),
	Str8L("Space"),
	Str8L("Enter"),
	Str8L("Ctrl"),
	Str8L("Shift"),
	Str8L("Alt"),
	Str8L("Up"),
	Str8L("Left"),
	Str8L("Down"),
	Str8L("Right"),
	Str8L("Page Up"),
	Str8L("Page Down"),
	Str8L("Home"),
	Str8L("End"),
	Str8L("Forward Slash"),
	Str8L("Period"),
	Str8L("Comma"),
	Str8L("Quote"),
	Str8L("Left Bracket"),
	Str8L("Right Bracket"),
	Str8L("Insert"),
	Str8L("Left Mouse Button"),
	Str8L("Middle Mouse Button"),
	Str8L("Right Mouse Button"),
	Str8L("Semicolon"),
};

}// namespace pm
